"""
Print-batch lifecycle + sheet generation (BRD 5.4 #5-8).

DEMO NOTE: `mark-printed` moves the batch's orders straight to `ready_to_pack`
(not just `printed`), so the next stage has a queue to work from without an extra manual
click.
"""
import uuid
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response
from sqlmodel import Session, select

from app.api.deps import require_staff_role
from app.core.database import get_session
from app.models.staff import StaffRole
from app.models.order import FulfillmentStatus, Order
from app.models.print_batch import PrintBatch, PrintBatchStatus
from app.services import fulfillment
from app.services.labels import render_labels_pdf_pages
from app.services.rendering import render_output
from app.services.serializers import order_summary
from app.services.sheet_layout import build_sheets

router = APIRouter(prefix="/api/ops", tags=["ops-batches"])


def _batch_orders(db: Session, batch_id: uuid.UUID) -> list[Order]:
    """Members of a batch in a DETERMINISTIC order.

    The explicit order_by is load-bearing, not cosmetic: the print sheets and
    the shipping labels are generated by two separate requests, and staff pair
    them physically (nth cut block goes in the envelope with the nth label).
    Without a stable sort Postgres may return the rows in a different order
    for the two calls and the pairing silently goes wrong.
    """
    return db.exec(
        select(Order)
        .where(Order.batch_id == batch_id)
        .order_by(Order.created_at, Order.order_code)
    ).all()


def _get_batch(db: Session, batch_id: uuid.UUID) -> PrintBatch:
    batch = db.get(PrintBatch, batch_id)
    if not batch:
        raise HTTPException(status_code=404, detail="بچ یافت نشد")
    return batch


@router.get("/batches")
def list_batches(
    db: Session = Depends(get_session),
    _=Depends(require_staff_role(StaffRole.ATELIER)),
):
    batches = db.exec(select(PrintBatch).order_by(PrintBatch.created_at.desc())).all()

    # Print size / paper type aren't stored on the batch - every order in a
    # batch is constrained to share them (see ops_orders.create_batch), so
    # they're derived from the members instead of duplicating them in a new
    # column. One query for all batches on the page, not one per batch.
    member_specs: dict[uuid.UUID, tuple[str, str]] = {}
    batch_ids = [b.id for b in batches]
    if batch_ids:
        rows = db.exec(
            select(Order.batch_id, Order.size, Order.paper_type).where(
                Order.batch_id.in_(batch_ids)
            )
        ).all()
        for bid, size, paper in rows:
            member_specs.setdefault(bid, (size.value, paper.value))

    return [
        {
            "id": str(b.id),
            "code": b.code,
            "sheet_size": b.sheet_size.value,
            "print_size": member_specs.get(b.id, (None, None))[0],
            "paper_type": member_specs.get(b.id, (None, None))[1],
            "status": b.status.value,
            "order_count": b.order_count,
            "piece_count": b.piece_count,
            "sheet_count": b.sheet_count,
            "created_at": b.created_at.isoformat(),
        }
        for b in batches
    ]


@router.get("/batches/{batch_id}")
def get_batch(
    batch_id: uuid.UUID,
    db: Session = Depends(get_session),
    _=Depends(require_staff_role(StaffRole.ATELIER)),
):
    batch = _get_batch(db, batch_id)
    orders = _batch_orders(db, batch.id)
    return {
        "id": str(batch.id),
        "code": batch.code,
        "sheet_size": batch.sheet_size.value,
        "print_size": orders[0].size.value if orders else None,
        "paper_type": orders[0].paper_type.value if orders else None,
        "status": batch.status.value,
        "order_count": batch.order_count,
        "piece_count": batch.piece_count,
        "sheet_count": batch.sheet_count,
        "orders": [order_summary(db, o) for o in orders],
    }


def _set_batch_and_orders(
    db: Session,
    batch: PrintBatch,
    batch_status: PrintBatchStatus,
    order_status: FulfillmentStatus,
) -> None:
    batch.status = batch_status
    db.add(batch)
    for order in _batch_orders(db, batch.id):
        order.fulfillment_status = order_status
        order.updated_at = datetime.utcnow()
        db.add(order)
    db.commit()


@router.post("/batches/{batch_id}/start-printing")
def start_printing(
    batch_id: uuid.UUID,
    db: Session = Depends(get_session),
    _=Depends(require_staff_role(StaffRole.ATELIER)),
):
    batch = _get_batch(db, batch_id)
    if batch.status != PrintBatchStatus.QUEUED:
        raise HTTPException(status_code=400, detail="فقط بچ‌های در صف قابل شروع چاپ هستند")
    _set_batch_and_orders(db, batch, PrintBatchStatus.PRINTING, FulfillmentStatus.PRINTING)
    return {"ok": True, "status": batch.status.value}


@router.post("/batches/{batch_id}/mark-printed")
def mark_printed(
    batch_id: uuid.UUID,
    db: Session = Depends(get_session),
    _=Depends(require_staff_role(StaffRole.ATELIER)),
):
    batch = _get_batch(db, batch_id)
    if batch.status != PrintBatchStatus.PRINTING:
        raise HTTPException(status_code=400, detail="فقط بچ در حال چاپ قابل اتمام است")
    _set_batch_and_orders(db, batch, PrintBatchStatus.PRINTED, FulfillmentStatus.READY_TO_PACK)
    return {"ok": True, "status": batch.status.value}


@router.get("/batches/{batch_id}/sheets")
def batch_sheets(
    batch_id: uuid.UUID,
    db: Session = Depends(get_session),
    _=Depends(require_staff_role(StaffRole.ATELIER)),
    format: str = Query(default="pdf"),
):
    batch = _get_batch(db, batch_id)
    orders = _batch_orders(db, batch.id)
    if not orders:
        raise HTTPException(status_code=400, detail="این بچ سفارشی ندارد")

    sheet_orders = fulfillment.build_sheet_orders(db, orders)
    images = build_sheets(sheet_orders, batch.sheet_size)

    batch.sheet_count = len(images)
    db.add(batch)
    db.commit()

    payload, media_type = render_output(images, format)
    ext = "pdf" if media_type == "application/pdf" else "png"
    return Response(
        content=payload,
        media_type=media_type,
        headers={"Content-Disposition": f'inline; filename="{batch.code}.{ext}"'},
    )


@router.get("/batches/{batch_id}/labels")
def batch_labels(
    batch_id: uuid.UUID,
    db: Session = Depends(get_session),
    _=Depends(require_staff_role(StaffRole.ATELIER)),
    format: str = Query(default="pdf"),
):
    """Shipping labels for every order in the batch, in the SAME order as the
    print sheets (both go through `_batch_orders`), so staff can pair the nth
    cut block with the nth label. Defaults to PDF because render_output only
    keeps the first page when asked for PNG.
    """
    batch = _get_batch(db, batch_id)
    orders = _batch_orders(db, batch.id)
    if not orders:
        raise HTTPException(status_code=400, detail="این بچ سفارشی ندارد")

    labels = [fulfillment.build_label_data(db, o) for o in orders]
    images = render_labels_pdf_pages(labels)

    payload, media_type = render_output(images, format)
    ext = "pdf" if media_type == "application/pdf" else "png"
    return Response(
        content=payload,
        media_type=media_type,
        headers={"Content-Disposition": f'inline; filename="{batch.code}-labels.{ext}"'},
    )
