"""add gender/outfit fields and print pricing

Revision ID: 2357b310cd8f
Revises: b28d42b264ed
Create Date: 2026-07-31 15:05:46.114299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2357b310cd8f'
down_revision = 'b28d42b264ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
