"""add order management (atelier ops panels)

Revision ID: b381e25f90d3
Revises: d267497a6a52
Create Date: 2026-08-05 17:10:23.976253

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b381e25f90d3'
down_revision = 'd267497a6a52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The two enums added to the existing `orders` table via add_column are
    # created explicitly first: when an added column carries a server_default,
    # Alembic skips the implicit CREATE TYPE, so we must emit it ourselves.
    bind = op.get_bind()
    postgresql.ENUM(
        'REGISTERED', 'QUEUED', 'PRINTING', 'PRINTED', 'QC_PENDING',
        'QC_REJECTED', 'SORTING', 'READY_TO_PACK', 'PACKING', 'PACKED',
        'READY_TO_SHIP', 'HANDED_TO_POST', 'SHIPPED', 'DELIVERED',
        name='fulfillmentstatus',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'LOW_QUALITY', 'WRONG_COLOR', 'WRONG_CUT', 'INCOMPLETE_PRINT',
        'PAPER_DAMAGE', 'OTHER',
        name='qcrejectreason',
    ).create(bind, checkfirst=True)

    op.create_table('ateliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ateliers_username'), 'ateliers', ['username'], unique=True)
    op.create_table('operators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'ADMIN', name='operatorrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_username'), 'operators', ['username'], unique=True)
    op.create_table('print_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sheet_size', sa.Enum('SIZE_10X15', 'SIZE_A4', name='sheetsize'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PRINTING', 'PRINTED', name='printbatchstatus'), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('piece_count', sa.Integer(), nullable=False),
    sa.Column('sheet_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_batches_code'), 'print_batches', ['code'], unique=True)
    op.create_index(op.f('ix_print_batches_operator_id'), 'print_batches', ['operator_id'], unique=False)
    op.create_index(op.f('ix_print_batches_status'), 'print_batches', ['status'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('handed_to_post_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_code'), 'shipments', ['code'], unique=True)
    op.create_index(op.f('ix_shipments_operator_id'), 'shipments', ['operator_id'], unique=False)
    # order_code is NOT NULL + unique, but pre-existing orders have none, so
    # add it nullable, backfill a stable ORD-NNNNNN per row, then enforce NOT
    # NULL. The unique index below is created after the backfill.
    op.add_column('orders', sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute(
        """
        UPDATE orders o SET order_code = sub.code
        FROM (
            SELECT id,
                   'ORD-' || lpad(
                       (row_number() OVER (ORDER BY created_at, id))::text, 6, '0'
                   ) AS code
            FROM orders
        ) sub
        WHERE o.id = sub.id
        """
    )
    op.alter_column('orders', 'order_code', nullable=False)

    op.add_column('orders', sa.Column('atelier_id', sa.Uuid(), nullable=True))
    # fulfillment_status is NOT NULL with no per-row value yet; give existing
    # paid orders the initial 'REGISTERED' stage via a temporary server
    # default, then drop the default so new rows come from the app model.
    op.add_column('orders', sa.Column('fulfillment_status', postgresql.ENUM('REGISTERED', 'QUEUED', 'PRINTING', 'PRINTED', 'QC_PENDING', 'QC_REJECTED', 'SORTING', 'READY_TO_PACK', 'PACKING', 'PACKED', 'READY_TO_SHIP', 'HANDED_TO_POST', 'SHIPPED', 'DELIVERED', name='fulfillmentstatus', create_type=False), nullable=False, server_default='REGISTERED'))
    op.alter_column('orders', 'fulfillment_status', server_default=None)
    op.add_column('orders', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('shipment_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('tracking_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('qc_reject_reason', postgresql.ENUM('LOW_QUALITY', 'WRONG_COLOR', 'WRONG_CUT', 'INCOMPLETE_PRINT', 'PAPER_DAMAGE', 'OTHER', name='qcrejectreason', create_type=False), nullable=True))
    op.add_column('orders', sa.Column('actual_piece_count', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('packing_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_orders_atelier_id'), 'orders', ['atelier_id'], unique=False)
    op.create_index(op.f('ix_orders_batch_id'), 'orders', ['batch_id'], unique=False)
    op.create_index(op.f('ix_orders_fulfillment_status'), 'orders', ['fulfillment_status'], unique=False)
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_orders_shipment_id'), 'orders', ['shipment_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'shipments', ['shipment_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'print_batches', ['batch_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'ateliers', ['atelier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_shipment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_fulfillment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_batch_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_atelier_id'), table_name='orders')
    op.drop_column('orders', 'packing_checklist')
    op.drop_column('orders', 'actual_piece_count')
    op.drop_column('orders', 'qc_reject_reason')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'tracking_code')
    op.drop_column('orders', 'shipment_id')
    op.drop_column('orders', 'batch_id')
    op.drop_column('orders', 'fulfillment_status')
    op.drop_column('orders', 'atelier_id')
    op.drop_column('orders', 'order_code')
    op.drop_index(op.f('ix_shipments_operator_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_code'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_print_batches_status'), table_name='print_batches')
    op.drop_index(op.f('ix_print_batches_operator_id'), table_name='print_batches')
    op.drop_index(op.f('ix_print_batches_code'), table_name='print_batches')
    op.drop_table('print_batches')
    op.drop_index(op.f('ix_operators_username'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_ateliers_username'), table_name='ateliers')
    op.drop_table('ateliers')
    # ### end Alembic commands ###

    # Postgres keeps enum types around after their columns/tables are dropped,
    # so drop them explicitly or a re-upgrade would hit "type already exists".
    bind = op.get_bind()
    for enum_name in (
        'fulfillmentstatus', 'qcrejectreason',
        'printbatchstatus', 'sheetsize', 'operatorrole',
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
