"""add gender/outfit fields and print pricing

Revision ID: d267497a6a52
Revises: 2357b310cd8f
Create Date: 2026-07-31 15:07:04.021382

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd267497a6a52'
down_revision = '2357b310cd8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
